version: '3.8'
services:
  metabase:
    image: stephaneturquay/metabase-arm64:latest
    ports:
      - "${PORT:-3000}:3000"
    # environment:
    #   MB_JETTY_PORT: "${PORT:-3000}"
    #   MB_DB_TYPE: postgres
    #   MB_DB_DBNAME: mydatabase
    #   MB_DB_PORT: 5432
    #   MB_DB_USER: myuser
    #   MB_DB_PASS: mypassword
    #   MB_DB_HOST: localhost
