version: '3.8'
services:
  metabase:
    image: stephaneturquay/metabase-postgres-arm64:latest
    ports:
      - "${PORT:-3000}:3000"
    environment:
      MB_JETTY_PORT: "${PORT:-4000}"
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabaseuser
      MB_DB_PASS: yourpassword
      MB_DB_HOST: db
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: metabaseuser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: metabaseappdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
